-- Create the currency_exchange_rates table
create table public.currency_exchange_rates (
  id bigint generated by default as identity primary key,
  from_currency text not null,
  to_currency text not null,
  rate numeric not null,
  source text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.currency_exchange_rates enable row level security;

-- Create policies
-- Allow read access to everyone (authenticated and anonymous)
create policy "Allow public read access"
  on public.currency_exchange_rates
  for select
  using (true);

-- Allow write access only to authenticated users (or restrict to admins if preferred)
create policy "Allow authenticated insert"
  on public.currency_exchange_rates
  for insert
  with check (auth.role() = 'authenticated');

create policy "Allow authenticated update"
  on public.currency_exchange_rates
  for update
  using (auth.role() = 'authenticated');

create policy "Allow authenticated delete"
  on public.currency_exchange_rates
  for delete
  using (auth.role() = 'authenticated');

-- Create a trigger to automatically update updated_at
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger handle_updated_at
  before update on public.currency_exchange_rates
  for each row
  execute procedure public.handle_updated_at();
