-- =================================================================
-- OUSSAMA AUTO - COMPLETE SUPABASE DATABASE SETUP
-- =================================================================
-- Run this ENTIRE script in Supabase SQL Editor (one go).
-- It creates all tables, functions, policies, triggers, and storage.
-- WARNING: This will DROP and recreate all tables (clean slate).
-- =================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =================================================================
-- DROP EXISTING TABLES (clean slate - order matters for foreign keys)
-- =================================================================
DROP TABLE IF EXISTS public.attendance_logs CASCADE;
DROP TABLE IF EXISTS public.employees CASCADE;
DROP TABLE IF EXISTS public.financial_summaries CASCADE;
DROP TABLE IF EXISTS public.documents CASCADE;
DROP TABLE IF EXISTS public.settings CASCADE;
DROP TABLE IF EXISTS public.currency_exchange_rates CASCADE;
DROP TABLE IF EXISTS public.financial_transactions CASCADE;
DROP TABLE IF EXISTS public.shipping_forms CASCADE;
DROP TABLE IF EXISTS public.car_inventory CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- =================================================================
-- 1. PROFILES (Extends Supabase Auth)
-- =================================================================
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
    role TEXT DEFAULT 'admin',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- =================================================================
-- 2. ORDERS
-- =================================================================
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_number TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'Pending',
    customer_name TEXT,
    customer_phone TEXT,
    customer_email TEXT,
    customer_wilaya TEXT,
    car_brand TEXT,
    car_model TEXT,
    car_budget TEXT,
    car_custom_budget TEXT,
    notes TEXT,
    source TEXT,
    order_data JSONB,
    added_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- =================================================================
-- 3. CAR INVENTORY
-- =================================================================
CREATE TABLE IF NOT EXISTS public.car_inventory (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    brand TEXT NOT NULL,
    model TEXT NOT NULL,
    year INTEGER NOT NULL,
    color TEXT,
    mileage INTEGER,
    vin_number TEXT,
    vin TEXT,
    purchase_price NUMERIC,
    selling_price NUMERIC,
    margin NUMERIC,
    currency TEXT DEFAULT 'KRW',
    location TEXT NOT NULL,
    status TEXT DEFAULT 'Available',
    photos_urls TEXT[],
    photos TEXT[],
    video_url TEXT,
    assigned_to_order TEXT,
    assigned_to_buyer TEXT,
    buyer_type TEXT,
    notes TEXT,
    added_by UUID REFERENCES auth.users(id),
    added_by_name TEXT,
    buying_price_krw NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    sold_at TIMESTAMP WITH TIME ZONE
);

-- =================================================================
-- 4. SHIPPING FORMS
-- =================================================================
CREATE TABLE IF NOT EXISTS public.shipping_forms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_model TEXT NOT NULL,
    vin_number TEXT NOT NULL,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT NOT NULL DEFAULT '',
    address TEXT NOT NULL DEFAULT '',
    passport_number TEXT NOT NULL DEFAULT '',
    code_postal TEXT NOT NULL DEFAULT '',
    zip_number TEXT NOT NULL DEFAULT '',
    vehicle_photos_urls TEXT,
    pdf_url TEXT,
    status TEXT DEFAULT 'Pending',
    notes TEXT,
    passport_photo_url TEXT,
    id_card_url TEXT,
    id_card_number TEXT,
    id_card_back_url TEXT,
    added_by UUID REFERENCES auth.users(id),
    shipping_provider TEXT,
    shipment_month TEXT,
    related_transaction_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- =================================================================
-- 5. FINANCIAL TRANSACTIONS
-- =================================================================
CREATE TABLE IF NOT EXISTS public.financial_transactions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    type TEXT NOT NULL,
    category TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    original_amount NUMERIC,
    currency TEXT DEFAULT 'DZD',
    description TEXT NOT NULL,
    payment_method TEXT,
    payment_status TEXT DEFAULT 'Paid',
    paid_amount NUMERIC,
    related_order_id TEXT,
    related_order_number TEXT,
    related_car_id UUID,
    transaction_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),

    -- Seller / Buyer / Commission
    seller_name TEXT,
    seller_commission NUMERIC,
    buyer_name TEXT,
    buyer_commission NUMERIC,
    bureau_commission NUMERIC,

    -- Car Details
    car_brand TEXT,
    car_model TEXT,
    car_year NUMERIC,
    car_vin TEXT,
    car_milage NUMERIC,
    car_buying_price NUMERIC,
    car_color TEXT,

    -- Currency Exchange
    buying_currency TEXT,
    original_buying_price NUMERIC,
    exchange_rate_dzd_usdt NUMERIC,
    exchange_rate_usdt_krw NUMERIC,
    is_paid_in_korea BOOLEAN,
    paid_in_korea_date TIMESTAMP WITH TIME ZONE,

    -- Customer
    customer_name TEXT,
    customer_phone TEXT,
    customer_email TEXT,
    customer_postal_code TEXT,
    customer_address TEXT,
    shipping_price NUMERIC,

    -- Shipping Form Fields
    passport_number TEXT,
    passport_photo_url TEXT,
    id_card_url TEXT,
    id_card_back_url TEXT,
    vehicle_photos_urls TEXT[],

    added_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- =================================================================
-- 6. CURRENCY EXCHANGE RATES
-- =================================================================
CREATE TABLE IF NOT EXISTS public.currency_exchange_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_currency TEXT NOT NULL,
    to_currency TEXT NOT NULL,
    rate NUMERIC NOT NULL,
    source TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =================================================================
-- 7. FINANCIAL SUMMARIES
-- =================================================================
CREATE TABLE IF NOT EXISTS public.financial_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_type TEXT NOT NULL,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    total_income NUMERIC,
    total_expenses NUMERIC,
    net_profit NUMERIC,
    total_transactions INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- =================================================================
-- 8. DOCUMENTS
-- =================================================================
CREATE TABLE IF NOT EXISTS public.documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_number TEXT NOT NULL,
    customer_reference TEXT,
    document_type TEXT DEFAULT 'general',
    document_data JSONB,
    file_paths TEXT[],
    upload_status TEXT,
    email_sent BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- =================================================================
-- 9. SETTINGS
-- =================================================================
CREATE TABLE IF NOT EXISTS public.settings (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =================================================================
-- 10. EMPLOYEES
-- =================================================================
CREATE TABLE IF NOT EXISTS public.employees (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    full_name TEXT NOT NULL,
    role TEXT DEFAULT 'Staff',
    status TEXT DEFAULT 'active',
    hourly_rate NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =================================================================
-- 11. ATTENDANCE LOGS
-- =================================================================
CREATE TABLE IF NOT EXISTS public.attendance_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    employee_id UUID REFERENCES public.employees(id) ON DELETE CASCADE NOT NULL,
    clock_in TIMESTAMP WITH TIME ZONE NOT NULL,
    clock_out TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'present',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =================================================================
-- INDEXES
-- =================================================================
CREATE INDEX IF NOT EXISTS idx_shipping_forms_transaction_id ON shipping_forms(related_transaction_id);
CREATE INDEX IF NOT EXISTS idx_shipping_forms_shipment_month ON shipping_forms(shipment_month);

-- =================================================================
-- HELPER FUNCTIONS
-- =================================================================

-- Auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, role)
    VALUES (NEW.id, 'admin');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to auto-create profile
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER handle_updated_at
    BEFORE UPDATE ON public.currency_exchange_rates
    FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- Check if user is admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role = 'admin'
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =================================================================
-- ENABLE ROW LEVEL SECURITY
-- =================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.car_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipping_forms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.currency_exchange_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_logs ENABLE ROW LEVEL SECURITY;

-- =================================================================
-- RLS POLICIES
-- =================================================================

-- === PROFILES ===
CREATE POLICY "Allow authenticated full access to profiles" ON public.profiles
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- === ORDERS ===
CREATE POLICY "Allow authenticated read orders" ON public.orders
    FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated insert orders" ON public.orders
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow owner/admin update orders" ON public.orders
    FOR UPDATE USING ((auth.uid() = added_by) OR public.is_admin());
CREATE POLICY "Allow owner/admin delete orders" ON public.orders
    FOR DELETE USING ((auth.uid() = added_by) OR public.is_admin());

-- === CAR INVENTORY ===
CREATE POLICY "Allow authenticated read car_inventory" ON public.car_inventory
    FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated insert car_inventory" ON public.car_inventory
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow owner/admin update car_inventory" ON public.car_inventory
    FOR UPDATE USING ((auth.uid() = added_by) OR public.is_admin());
CREATE POLICY "Allow owner/admin delete car_inventory" ON public.car_inventory
    FOR DELETE USING ((auth.uid() = added_by) OR public.is_admin());

-- === SHIPPING FORMS ===
CREATE POLICY "Allow authenticated read shipping_forms" ON public.shipping_forms
    FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated insert shipping_forms" ON public.shipping_forms
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow owner/admin update shipping_forms" ON public.shipping_forms
    FOR UPDATE USING ((auth.uid() = added_by) OR public.is_admin());
CREATE POLICY "Allow owner/admin delete shipping_forms" ON public.shipping_forms
    FOR DELETE USING ((auth.uid() = added_by) OR public.is_admin());

-- === FINANCIAL TRANSACTIONS (Admin Only) ===
CREATE POLICY "Admins full access financial_transactions" ON public.financial_transactions
    FOR ALL USING (public.is_admin());

-- === CURRENCY EXCHANGE RATES (Public read, authenticated write) ===
CREATE POLICY "Allow public read exchange rates" ON public.currency_exchange_rates
    FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert exchange rates" ON public.currency_exchange_rates
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated update exchange rates" ON public.currency_exchange_rates
    FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated delete exchange rates" ON public.currency_exchange_rates
    FOR DELETE USING (auth.role() = 'authenticated');

-- === FINANCIAL SUMMARIES ===
CREATE POLICY "Admin full access financial_summaries" ON public.financial_summaries
    FOR ALL USING (public.is_admin());

-- === DOCUMENTS ===
CREATE POLICY "Allow authenticated full access documents" ON public.documents
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- === SETTINGS ===
CREATE POLICY "Allow authenticated full access settings" ON public.settings
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- === EMPLOYEES (Admin Only) ===
CREATE POLICY "Admins full control employees" ON public.employees
    FOR ALL TO authenticated
    USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin')
    WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- === ATTENDANCE LOGS (Admin Only) ===
CREATE POLICY "Admins full control attendance_logs" ON public.attendance_logs
    FOR ALL TO authenticated
    USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin')
    WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- =================================================================
-- STORAGE BUCKETS
-- =================================================================
-- Create these manually in Supabase Dashboard > Storage:
--   1. "car-images"   (public bucket)
--   2. "shipping-docs" (public bucket)
--
-- Then run these policies for each bucket:

-- For car-images bucket:
-- INSERT policy: Allow authenticated uploads
--   (bucket_id = 'car-images' AND auth.role() = 'authenticated')
-- SELECT policy: Allow public reads
--   (bucket_id = 'car-images')
-- DELETE policy: Allow authenticated deletes
--   (bucket_id = 'car-images' AND auth.role() = 'authenticated')

-- For shipping-docs bucket:
-- INSERT policy: Allow authenticated uploads
--   (bucket_id = 'shipping-docs' AND auth.role() = 'authenticated')
-- SELECT policy: Allow public reads
--   (bucket_id = 'shipping-docs')
-- DELETE policy: Allow authenticated deletes
--   (bucket_id = 'shipping-docs' AND auth.role() = 'authenticated')

-- =================================================================
-- DONE! Now:
-- 1. Create a user account via Supabase Auth (Dashboard > Authentication)
-- 2. Create storage buckets: "car-images" and "shipping-docs"
-- 3. Set bucket policies as described above
-- 4. Add your domain to Authentication > URL Configuration:
--    - Site URL: https://oussamaauto.com
--    - Redirect URLs: https://oussamaauto.com/**
-- =================================================================
