import { createContext, ReactNode, useContext, useEffect, useState } from 'react'

type Language = 'en' | 'fr' | 'ar'

interface LanguageContextType {
    language: Language
    setLanguage: (lang: Language) => void
    t: any // Using any for now to avoid complex type definitions during migration
    dir: 'ltr' | 'rtl'
}

const translations = {
    en: {
        common: {
            dashboard: 'Dashboard',
            orders: 'Orders',
            inventory: 'Inventory',
            finance: 'Finance',
            shipping: 'Shipping',
            signOut: 'Sign Out',
            viewDetails: 'View Details',
            cancel: 'Cancel',
            save: 'Save',
            allStatus: 'All Status',
            available: 'Available',
            reserved: 'Reserved',
            sold: 'Sold',
            loading: 'Loading...',
            noCars: 'No cars found',
            noImage: 'No Image',
            assign: 'Assign',
            share: 'Share',
            model: 'Model',
            year: 'Year',
            notes: 'Notes',
            back: 'Back',
            edit: 'Edit'
        },
        dashboard: {
            totalOrders: 'Total Orders',
            totalRevenue: 'Total Revenue',
            inventory: 'Inventory',
            shippingForms: 'Shipping Forms',
            recentActivity: 'Recent Activity',
            quickActions: 'Quick Actions',
            newOrder: 'New Order',
            newTransaction: 'New Transaction',
            addCar: 'Add Car',
            shippingForm: 'Shipping Form',
        },
        orders: {
            title: 'Orders',
            newOrder: 'New Order',
            searchPlaceholder: 'Search by name, reference, or car...',
            allStatus: 'All Status',
            loading: 'Loading orders...',
            noOrders: 'No orders found',
            car: 'Car',
            budget: 'Budget',
            wilaya: 'Wilaya',
            status: {
                pending: 'Pending',
                confirmed: 'Confirmed',
                bought: 'Bought',
                shipped: 'Shipped',
                customs: 'In Customs',
                ready: 'Ready',
                delivered: 'Delivered',
                cancelled: 'Cancelled',
            }
        },
        inventory: {
            title: 'Inventory',
            addCar: 'Add Car',
            searchPlaceholder: 'Search by brand, model, or VIN...',
            allStatus: 'All Status',
            available: 'Available',
            reserved: 'Reserved',
            sold: 'Sold',
            loading: 'Loading inventory...',
            noCars: 'No cars found',
            noImage: 'No Image',
            assign: 'Assign',
            share: 'Share',
            model: 'Model',
            year: 'Year',
            location: 'Location',
            color: 'Color',
            edit: 'Edit'
        },
        finance: {
            title: 'Finance',
            newTransaction: 'New Transaction',
            searchPlaceholder: 'Search transactions...',
            allStatus: 'All Status',
            paid: 'Paid',
            pending: 'Pending',
            unpaid: 'Unpaid',
            partial: 'Partial',
            loading: 'Loading transactions...',
            noTransactions: 'No transactions found',
            confirmDelete: 'Are you sure you want to delete this transaction?',
            errorDelete: 'Error deleting transaction',
            netProfit: 'Net Profit',
            seller: 'Seller',
            buyer: 'Buyer',
            paidInKorea: 'Paid in Korea',
            remainingAmount: 'Remaining Amount',
            commissions: 'Commissions',
            officeCommission: 'Office Commission',
            totalCommissions: 'Total Commissions',
            viewDetails: 'View Details',
            clientName: 'Client Name',
            clientPhone: 'Client Phone',
            mileage: 'Mileage',
            currency: 'Currency',
            originalPrice: 'Original Price',
            buyingPriceDZD: 'Buying Price (DZD)',
            sellingPrice: 'Selling Price',
            exchangeRate: 'Exchange Rate',
            carBuyingPrice: 'Car Buying Price',
            profit: 'Profit'
        },
        shipping: {
            title: 'Shipping',
            newForm: 'New Form',
            searchPlaceholder: 'Search by name, vehicle, or VIN...',
            allStatus: 'All Status',
            pending: 'Pending',
            completed: 'Completed',
            loading: 'Loading shipping forms...',
            noForms: 'No shipping forms found',
            phone: 'Phone',
            vin: 'VIN',
            date: 'Date',
        },
        modals: {
            assignCarTitle: 'Assign Car to Order',
            searchOrders: 'Search orders...',
            loadingOrders: 'Loading orders...',
            noOrders: 'No eligible orders found',
            cancel: 'Cancel',
            assignOrder: 'Assign Order',
            assigning: 'Assigning...',
            shareCarTitle: 'Share Car',
            selectOrders: 'Select orders to share this car with:',
            noConfirmedOrders: 'No confirmed orders found',
            lookingFor: 'Looking for',
            shareWhatsApp: 'Share via WhatsApp',
            shippingInfoTitle: 'Update Shipping Info',
            waitingForTracking: 'Waiting for tracking number',
            shippingCompany: 'Shipping Company',
            optional: '(Optional)',
            selectCompany: 'Select Company',
            trackingNumber: 'Tracking Number',
            route: 'Route',
            updateStatus: 'Update Status',
        },
        forms: {
            fullName: 'Full Name',
            phone: 'Phone Number',
            email: 'Email',
            wilaya: 'Wilaya',
            idCard: 'ID Card Number',
            carBrand: 'Car Brand',
            carModel: 'Car Model',
            budget: 'Budget',
            customBudget: 'Custom Budget',
            notes: 'Notes',
            cancel: 'Cancel',
            save: 'Save',
            create: 'Create',
            saving: 'Saving...',
            back: 'Back',
            customerInfo: 'Customer Info',
            vehicleDetails: 'Vehicle Details',
            createOrder: 'Create Order',
            createTransaction: 'Create Transaction',
            updateStatus: 'Update Status',
            selectCar: 'Select Car',
            searchCars: 'Search Cars...',
            transactionInfo: 'Transaction Info',
            clientDetails: 'Client Details',
            commissionsParties: 'Commissions & Parties',
            additionalInfo: 'Additional Info',
            basicInfo: 'Basic Info',
            pricingLocation: 'Pricing & Location',
            media: 'Media',
            uploadPhoto: 'Upload Photo',
            uploadVideo: 'Upload Video',
            color: 'Color',
            location: 'Location',
            buyingPrice: 'Buying Price',
            sellingPrice: 'Selling Price',
        },
        settings: {
            title: 'Settings',
            exchangeRates: 'Exchange Rates',
            save: 'Save Settings',
            saved: 'Settings saved successfully',
        }
    },
    ar: {
        common: {
            dashboard: 'لوحة التحكم',
            orders: 'الطلبات',
            inventory: 'المخزون',
            finance: 'المالية',
            shipping: 'الشحن',
            signOut: 'تسجيل الخروج',
            viewDetails: 'عرض التفاصيل',
            cancel: 'إلغاء',
            save: 'حفظ',
            allStatus: 'كل الحالات',
            available: 'متاح',
            reserved: 'محجوز',
            sold: 'مباع',
            loading: 'جاري التحميل...',
            noCars: 'لا توجد سيارات',
            noImage: 'لا توجد صورة',
            assign: 'تعيين',
            share: 'مشاركة',
            model: 'الموديل',
            year: 'السنة',
            notes: 'ملاحظات',
            back: 'رجوع',
            edit: 'تعديل'
        },
        dashboard: {
            totalOrders: 'إجمالي الطلبات',
            totalRevenue: 'إجمالي الإيرادات',
            inventory: 'المخزون',
            shippingForms: 'نماذج الشحن',
            recentActivity: 'النشاط الأخير',
            quickActions: 'إجراءات سريعة',
            newOrder: 'طلب جديد',
            newTransaction: 'معاملة جديدة',
            addCar: 'إضافة سيارة',
            shippingForm: 'نموذج شحن',
        },
        orders: {
            title: 'الطلبات',
            newOrder: 'طلب جديد',
            searchPlaceholder: 'البحث في الطلبات...',
            allStatus: 'كل الحالات',
            loading: 'جاري تحميل الطلبات...',
            noOrders: 'لا توجد طلبات',
            car: 'السيارة',
            budget: 'الميزانية',
            wilaya: 'الولاية',
            status: {
                pending: 'قيد الانتظار',
                confirmed: 'مؤكد',
                bought: 'تم الشراء',
                shipped: 'تم الشحن',
                customs: 'في الجمارك',
                ready: 'جاهز',
                delivered: 'تم التوصيل',
                cancelled: 'ملغي',
            }
        },
        inventory: {
            title: 'المخزون',
            addCar: 'إضافة سيارة',
            searchPlaceholder: 'بحث عن ماركة، موديل، أو رقم الهيكل...',
            allStatus: 'كل الحالات',
            available: 'متاح',
            reserved: 'محجوز',
            sold: 'مباع',
            loading: 'جاري تحميل المخزون...',
            noCars: 'لا توجد سيارات',
            noImage: 'لا توجد صورة',
            assign: 'تعيين',
            share: 'مشاركة',
            model: 'الموديل',
            year: 'السنة',
            location: 'الموقع',
            color: 'اللون',
            edit: 'تعديل'
        },
        finance: {
            title: 'المالية',
            newTransaction: 'معاملة جديدة',
            searchPlaceholder: 'البحث في المعاملات...',
            allStatus: 'كل الحالات',
            paid: 'مدفوع',
            pending: 'قيد الانتظار',
            unpaid: 'غير مدفوع',
            partial: 'جزئي',
            loading: 'جاري تحميل المعاملات...',
            noTransactions: 'لا توجد معاملات',
            seller: 'البائع',
            buyer: 'المشتري',
            commissions: 'العمولات والوساطة',
            officeCommission: 'عمولة المكتب',
            totalCommissions: 'إجمالي العمولات',
            clientName: 'اسم العميل',
            clientPhone: 'هاتف العميل',
            mileage: 'عداد الكيلومترات',
            carBuyingPrice: 'سعر شراء السيارة',
            profit: 'الربح',
            netProfit: 'صافي الربح',
            remainingAmount: 'المبلغ المتبقي',
            currency: 'العملة',
            exchangeRate: 'سعر الصرف',
            originalPrice: 'السعر الأصلي',
            paidInKorea: 'تم الدفع في كوريا',
            viewDetails: 'عرض التفاصيل',
            buyingPriceDZD: 'سعر الشراء (DZD)',
            sellingPrice: 'سعر البيع',
            confirmDelete: 'هل أنت متأكد أنك تريد حذف هذه المعاملة؟',
            errorDelete: 'فشل حذف المعاملة',
        },
        shipping: {
            title: 'نماذج الشحن',
            newForm: 'نموذج جديد',
            searchPlaceholder: 'البحث في النماذج...',
            allStatus: 'كل الحالات',
            pending: 'قيد الانتظار',
            completed: 'مكتمل',
            loading: 'جاري تحميل النماذج...',
            noForms: 'لا توجد نماذج شحن',
            phone: 'الهاتف',
            vin: 'رقم الهيكل',
            date: 'التاريخ',
        },
        modals: {
            assignCarTitle: 'تعيين السيارة لطلب',
            shareCarTitle: 'مشاركة السيارة',
            selectOrders: 'اختر الطلبات المؤكدة لمشاركة هذه السيارة معها:',
            searchOrders: 'البحث في الطلبات...',
            loadingOrders: 'جاري تحميل الطلبات...',
            noOrders: 'لا توجد طلبات',
            noConfirmedOrders: 'لا توجد طلبات مؤكدة',
            lookingFor: 'يبحث عن',
            assignOrder: 'تعيين الطلب',
            assigning: 'جاري التعيين...',
            shareWhatsApp: 'مشاركة عبر واتساب',
            cancel: 'إلغاء',
            shippingInfoTitle: 'معلومات الشحن',
            waitingForTracking: 'تم الشحن لكن في انتظار رقم التتبع',
            shippingCompany: 'شركة الشحن',
            selectCompany: 'اختر شركة الشحن',
            trackingNumber: 'رقم التتبع',
            route: 'المسار',
            updateStatus: 'تحديث حالة الطلب',
            optional: '(اختياري)',
        },
        forms: {
            fullName: 'الاسم الكامل',
            phone: 'رقم الهاتف',
            email: 'البريد الإلكتروني',
            wilaya: 'الولاية',
            idCard: 'رقم بطاقة الهوية',
            carBrand: 'ماركة السيارة',
            carModel: 'موديل السيارة',
            budget: 'الميزانية',
            customBudget: 'ميزانية مخصصة',
            notes: 'ملاحظات',
            cancel: 'إلغاء',
            save: 'حفظ',
            create: 'إنشاء',
            saving: 'جاري الحفظ...',
            back: 'رجوع',
            customerInfo: 'معلومات العميل',
            vehicleDetails: 'تفاصيل المركبة',
            createOrder: 'إنشاء طلب',
            createTransaction: 'إنشاء معاملة',
            updateStatus: 'تحديث الحالة',
            selectCar: 'اختر السيارة',
            searchCars: 'البحث في السيارات...',
            transactionInfo: 'معلومات المعاملة',
            clientDetails: 'تفاصيل العميل',
            commissionsParties: 'العمولات والأطراف',
            additionalInfo: 'معلومات إضافية',
            basicInfo: 'المعلومات الأساسية',
            pricingLocation: 'التسعير والموقع',
            media: 'الوسائط',
            uploadPhoto: 'تحميل صورة',
            uploadVideo: 'تحميل فيديو',
            color: 'اللون',
            location: 'الموقع',
            buyingPrice: 'سعر الشراء',
            sellingPrice: 'سعر البيع',
        },
        settings: {
            title: 'الإعدادات',
            exchangeRates: 'أسعار الصرف',
            save: 'حفظ الإعدادات',
            saved: 'تم حفظ الإعدادات بنجاح',
        },
    },
    fr: {
        // Fallback or empty provided
        common: {
            dashboard: 'Tableau de bord',
            orders: 'Commandes',
            inventory: 'Stock',
            finance: 'Finance',
            shipping: 'Expédition',
            signOut: 'Déconnexion',
            viewDetails: 'Voir détails',
            cancel: 'Annuler',
            save: 'Enregistrer',
            allStatus: 'Tous les statuts',
            available: 'Disponible',
            reserved: 'Réservé',
            sold: 'Vendu',
            loading: 'Chargement...',
            noCars: 'Aucune voiture trouvée',
            noImage: 'Aucune image',
            assign: 'Attribuer',
            share: 'Partager',
            model: 'Modèle',
            year: 'Année',
            notes: 'Notes',
            back: 'Retour',
            edit: 'Modifier'
        },
        // ... Minimal FR stub for now to avoid crashes
    }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>('en')
    const dir = language === 'ar' ? 'rtl' : 'ltr'

    // Update document direction when language changes
    useEffect(() => {
        document.documentElement.dir = dir
        document.documentElement.lang = language
    }, [language, dir])


    const value: LanguageContextType = {
        language,
        setLanguage,
        t: translations[language] || translations.en,
        dir,
    }

    return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider')
    }
    return context
}
